### ISSUE TITLE
Add branching commands

### ISSUE THREAD

**Issue by voloda** [DevTrainings/GitTraining#8]
- branch
- checkout

**Comment by graywolf** [comment]
git branch summed up in 230b6e7347ce0434f64af2300fb09988b2b4e955

**Comment by graywolf** [comment]
@voloda can you check this if it's ok?

**Comment by voloda** [comment]
Overall looks good :+1:. Comments:
- `ls -l` should be `dir` in checkout 
- Using `notepad` instead of echo might be easier
- I think that next step should a _lab_ where you will play with these
- Also it might be easier to review on pull request :)

**Comment by graywolf** [comment]
> ls -l should be dir in checkout 

I changed it into something that works under powershell

> Using notepad instead of echo might be easier

tbh I don't see why.. why spawn notepad when the same thing can be accomplished with `echo` without leaving command line?

> I think that next step should a lab where you will play with these

for playing you would need marge imho. so lab for playing with it maybe after all the core commands?

> Also it might be easier to review on pull request :)

agree, trying that now
